services:
  - type: web
    name: scat-telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: API_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: CREDENTIALS_FILE
        sync: false
